spring:
  datasource:
    username: root
    password: root
    #mysql8
    url: jdbc:mysql://122.51.104.146:3307/mh?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      validation-query:
      filter:
        commons-log:
          statement-log-enabled: true
          statement-executable-sql-log-enable: true
  #    initialization-mode: always
#    schema: classpath:schema.sql
#    data: classpath:data.sql
  # jpa 配置
  jpa:
    database: mysql
    show-sql: true
    database-platform: mysql
    hibernate:
    #每次项目启动时数据库初始化策略
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    global-config:
#      db-config:
#        id-type: AUTO















#    druid:
#      url: jdbc:mysql://122.51.104.146:3307/mh?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      # 初始化物理连接个数
#      initial-size: 1
#      # 最大连接池数量
#      max-active: 20
#      # 最小连接池数量
#      min-idle: 10
#      # 获取连接时最大等待时间(ms)
#      max-wait: 60000
#      # 开启缓存preparedStatement(PSCache)
#      pool-prepared-statements: true
#      # 启用PSCache后，指定每个连接上PSCache的大小
#      max-pool-prepared-statement-per-connection-size: 20
#      # 用来检测连接是否有效的sql
#      validation-query: select 'x'
#      # 申请连接时不检测连接是否有效
#      test-on-borrow: false
#      # 归还连接时不检测连接是否有效
#      test-on-return: false
#      # 申请连接时检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效（不影响性能）
#      test-while-idle: true
#      # 检测连接的间隔时间，若连接空闲时间 >= minEvictableIdleTimeMillis，则关闭物理连接
#      time-between-eviction-runs-millis: 60000
#      # 连接保持空闲而不被驱逐的最小时间(ms)
#      min-evictable-idle-time-millis: 300000
#      # 配置监控统计拦截的filters（不配置则监控界面sql无法统计），监控统计filter:stat，日志filter:log4j，防御sql注入filter:wall
#      filters: stat,log4j,wall
#      # 支持合并多个DruidDataSource的监控数据
#      use-global-data-source-stat: true
#      # 通过connectProperties属性来打开mergeSql(Sql合并)功能；慢SQL记录(配置超过5秒就是慢，默认是3秒)

#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000